# Modules
- color: "fbca04"
  description: "This issue or pull request is related to authentication-policy module."
  name: ":floppy_disk: authentication-policy"
- color: "fbca04"
  description: "This issue or pull request is related to authenticator module."
  name: ":floppy_disk: authenticator"
- color: "fbca04"
  description: "This issue or pull request is related to authenticator-enrollment-policy module."
  name: ":floppy_disk: authenticator-enrollment-policy"
- color: "fbca04"
  description: "This issue or pull request is related to authorization-server module."
  name: ":floppy_disk: authorization-server"
- color: "fbca04"
  description: "This issue or pull request is related to bookmark-app module."
  name: ":floppy_disk: bookmark-app"
- color: "fbca04"
  description: "This issue or pull request is related to brand module."
  name: ":floppy_disk: brand"
- color: "fbca04"
  description: "This issue or pull request is related to global-session-policy module."
  name: ":floppy_disk: global-session-policy"
- color: "fbca04"
  description: "This issue or pull request is related to group module."
  name: ":floppy_disk: group"
- color: "fbca04"
  description: "This issue or pull request is related to group-rule module."
  name: ":floppy_disk: group-rule"
- color: "fbca04"
  description: "This issue or pull request is related to network-zone module."
  name: ":floppy_disk: network-zone"
- color: "fbca04"
  description: "This issue or pull request is related to oidc-app module."
  name: ":floppy_disk: oidc-app"
- color: "fbca04"
  description: "This issue or pull request is related to organization module."
  name: ":floppy_disk: organization"
- color: "fbca04"
  description: "This issue or pull request is related to password-policy module."
  name: ":floppy_disk: password-policy"
- color: "fbca04"
  description: "This issue or pull request is related to saml-app module."
  name: ":floppy_disk: saml-app"
- color: "fbca04"
  description: "This issue or pull request is related to user module."
  name: ":floppy_disk: user"
